service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: development
    PROJECTS_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PROJECTS_DYNAMODB_TABLE}"

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - .env.staging
    - .env.production
  include:
    - .env.development

functions:
  createProject:
    handler: app/handler.createProject
    events:
      - http:
          path: projects
          method: post
  updateProject:
    handler: app/handler.updateProject
    events:
      - http:
          path: projects/{id}
          method: put
  findProjects:
    handler: app/handler.findProjects
    events:
      - http:
          path: projects
          method: get
  findProject:
    handler: app/handler.findProject
    events:
      - http:
          path: projects/{id}
          method: get

  deleteProject:
    handler: app/handler.deleteProject
    events:
      - http:
          path: projects/{id}
          method: delete
