service: aws-serverless-example

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  bundle:
    ignorePackages:
      - pg-native

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  timeout: 300
  apiKeys:
    - todoAPI
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    DB_URL: ${env:DB_URL}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}

package:
  include:
    - features/**
    - models/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  listTodos:
    handler: features/read.listTodos
    events:
      - http:
          path: todos
          method: get

  getTodo:
    handler: features/read.getTodo
    events:
      - http:
          path: todo/{id}
          method: get
          private: true

  createTodo:
    handler: features/create.createTodo
    events:
      - http:
          path: todo
          method: post
          private: true

  deleteTodo:
    handler: features/delete.deleteTodo
    events:
      - http:
          path: todo/{id}
          method: delete
          private: true

  updateTodo:
    handler: features/update.updateTodo
    events:
      - http:
          path: todo/{id}
          method: patch
          private: true
